version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bazarweb'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
